
CXX		= $(DLPGENERATOR_CXX)
LD              = g++
LDFLAGS         += -Wl,-rpath,$(DLPGENERATOR_DIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O3 $(DLPGENERATOR_CXXSTDFLAG) -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = g++
SOFLAGS         = -g -fPIC -shared
